FROM --platform=linux/amd64 apache/airflow:2.9.3

RUN pip install --no-cache-dir airflow-provider-great-expectations==0.2.7 \
                                apache-airflow-providers-google==10.23.0 \
                                apache-airflow-providers-common-sql>=1.7.2
